name: Outpost
api: 5.3.0
version: 0.1.0-ALPHA
main: nicholass003\outpost\Outpost
author: nicholass003
permissions:
  outpost.command:
    default: op
  outpost.command.list:
    default: op
  outpost.command.remove:
    default: op
  outpost.command.set:
    default: op